[server]
sslCertFile = ".ssl/cert.pem"
sslKeyFile  = ".ssl/key.pem"

[theme]
base                  = "light"
primaryColor          = "#1DD6A4"
backgroundColor       = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor             = "#0D1F3C"
